### ISSUE TITLE
Create ScheduleRange

### ISSUE THREAD

**Issue by GuillermoDivan** [UlisesGS/SecretarioVirtual#18]
URL: http://localhost:8080/api/horario/crear
ACTION: POST.
JWT: admin (a generar la validación).

example body 
{
"day": "MONDAY",
"startsAt" : "18:30:00",
"endsAt" : "20:00:00",
"appointmentDuration" : 45,
"breakTime" : 5
}

example response 200. 
{
    "id": "773a92de-4f8f-4073-b5e8-7994509b9fe3",
    "day": "SUNDAY",
    "startsAt": "18:30:00",
    "endsAt": "19:15:00",
    "appointmentDuration": 45,
    "breakTime": 5,
    "appointmentsAmount": 1
}

**Comment by UlisesGS** [comment]
appointmentsAmount notifica la cantidad de ssesiones a tener con el rango y minutos(sesion,descanso) seleccionados.
